# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\MultitenantService:
    App\Service\ReservationQueryService:

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # SPA Command Handler pattern

    create_spa_command_handler:
      class: App\CommandHandler\Admin\CreateSPACommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\CreateSPA}
    edit_spa_command_handler:
      class: App\CommandHandler\Admin\EditSPACommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\EditSPA}
    delete_spa_command_handler:
      class: App\CommandHandler\Admin\DeleteSPACommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\DeleteSPA}

    # User Command Handler pattern

    create_user_command_handler:
      class: App\CommandHandler\Admin\CreateUserCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\CreateUser}
    edit_user_command_handler:
      class: App\CommandHandler\Admin\EditUserCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\EditUser}
    delete_user_command_handler:
      class: App\CommandHandler\Admin\DeleteUserCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Admin\DeleteUser}

    # Operator Command Handler pattern

    create_operator_command_handler:
      class: App\CommandHandler\Staff\Operator\CreateOperatorCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Operator\CreateOperator}

    edit_operator_command_handler:
      class: App\CommandHandler\Staff\Operator\EditOperatorCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Operator\EditOperator}

    delete_operator_command_handler:
      class: App\CommandHandler\Staff\Operator\DeleteOperatorCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Operator\DeleteOperator}

    # Treatment Command Handler pattern

    create_treatment_command_handler:
      class: App\CommandHandler\Staff\Treatment\CreateTreatmentCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Treatment\CreateTreatment}

    edit_treatment_command_handler:
      class: App\CommandHandler\Staff\Treatment\EditTreatmentCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Treatment\EditTreatment}

    delete_treatment_command_handler:
      class: App\CommandHandler\Staff\Treatment\DeleteTreatmentCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Treatment\DeleteTreatment}

  # Customer Command Handler pattern

    create_customer_command_handler:
      class: App\CommandHandler\Staff\Customer\CreateCustomerCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Customer\CreateCustomer}

    edit_customer_command_handler:
      class: App\CommandHandler\Staff\Customer\EditCustomerCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Customer\EditCustomer}

    delete_customer_command_handler:
      class: App\CommandHandler\Staff\Customer\DeleteCustomerCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Customer\DeleteCustomer}

  # Reservation Command Handler pattern

    create_Reservation_command_handler:
      class: App\CommandHandler\Staff\Reservation\CreateReservationCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Reservation\CreateReservation}

    edit_Reservation_command_handler:
      class: App\CommandHandler\Staff\Reservation\EditReservationCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Reservation\EditReservation}

    delete_Reservation_command_handler:
      class: App\CommandHandler\Staff\Reservation\DeleteReservationCommandHandler
      tags:
        - { name: command_handler, handles: App\Command\Staff\Reservation\DeleteReservation}
